// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JGwebTienda.Migrations
{
    [DbContext(typeof(JGwebTiendaContext))]
    partial class JGwebTiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JGwebTienda.Models.JGadornos", b =>
                {
                    b.Property<int>("JGadornosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JGadornosId"));

                    b.Property<string>("JGName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JGnavideno")
                        .HasColumnType("bit");

                    b.Property<decimal>("JGprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JGadornosId");

                    b.ToTable("JGadornos");
                });
#pragma warning restore 612, 618
        }
    }
}
